//go:generate go get github.com/jteeuwen/go-bindata/...
//go:generate go get github.com/elazarl/go-bindata-assetfs/...
//go:generate go-bindata-assetfs -pkg=assets -prefix=../assets ./static/...

package assets

import "github.com/elazarl/go-bindata-assetfs"

// AssetFS ...
func AssetFS() *assetfs.AssetFS {
	return assetFS()
}
